name: service-picker

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false

      - name: Install pre-commit dependencies
        run: |
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/go-critic/go-critic/cmd/gocritic@latest
          go install golang.org/x/lint/golint@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -gcflags=all=-l -coverprofile=coverage.out

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 1.2.3
